version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - /Users/docker/data/mongodb:/data/db
    ports:
    - 3101:27017
    restart: unless-stopped
  minio:
    image : minio/minio
    container_name: minio
    command: server /data
    environment:
    - MINIO_ROOT_USER=accesskey
    - MINIO_ROOT_PASSWORD=secretkey
    volumes:
    - /Users/docker/data/minio:/data
    ports:
    - 9000:9000
    restart: unless-stopped
  arc2:
    image : arc2_server
    container_name: arc2
    volumes:
    - /Users/docker/data/arc2:/data/arc2
    ports:
    - 5000:5000
    restart: unless-stopped
