# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util

import re  # noqa: E501

class Arc2Cache(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, date_begin=None, date_end=None, days=None, cache=None):  # noqa: E501
        """Arc2Cache - a model defined in OpenAPI

        :param date_begin: The date_begin of this Arc2Cache.  # noqa: E501
        :type date_begin: str
        :param date_end: The date_end of this Arc2Cache.  # noqa: E501
        :type date_end: str
        :param days: The days of this Arc2Cache.  # noqa: E501
        :type days: float
        :param cache: The cache of this Arc2Cache.  # noqa: E501
        :type cache: List[str]
        """
        self.openapi_types = {
            'date_begin': str,
            'date_end': str,
            'days': float,
            'cache': List[str]
        }

        self.attribute_map = {
            'date_begin': 'date_begin',
            'date_end': 'date_end',
            'days': 'days',
            'cache': 'cache'
        }

        self._date_begin = date_begin
        self._date_end = date_end
        self._days = days
        self._cache = cache

    @classmethod
    def from_dict(cls, dikt) -> 'Arc2Cache':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Arc2Cache of this Arc2Cache.  # noqa: E501
        :rtype: Arc2Cache
        """
        return util.deserialize_model(dikt, cls)

    @property
    def date_begin(self):
        """Gets the date_begin of this Arc2Cache.

        Rainfall cache start date in YYYYMMDD format  # noqa: E501

        :return: The date_begin of this Arc2Cache.
        :rtype: str
        """
        return self._date_begin

    @date_begin.setter
    def date_begin(self, date_begin):
        """Sets the date_begin of this Arc2Cache.

        Rainfall cache start date in YYYYMMDD format  # noqa: E501

        :param date_begin: The date_begin of this Arc2Cache.
        :type date_begin: str
        """
        if date_begin is not None and not re.search(r'^20[0-9]{6}$', date_begin):  # noqa: E501
            raise ValueError("Invalid value for `date_begin`, must be a follow pattern or equal to `/^20[0-9]{6}$/`")  # noqa: E501

        self._date_begin = date_begin

    @property
    def date_end(self):
        """Gets the date_end of this Arc2Cache.


        :return: The date_end of this Arc2Cache.
        :rtype: str
        """
        return self._date_end

    @date_end.setter
    def date_end(self, date_end):
        """Sets the date_end of this Arc2Cache.


        :param date_end: The date_end of this Arc2Cache.
        :type date_end: str
        """
        if date_end is not None and not re.search(r'^20[0-9]{6}$', date_end):  # noqa: E501
            raise ValueError("Invalid value for `date_end`, must be a follow pattern or equal to `/^20[0-9]{6}$/`")  # noqa: E501

        self._date_end = date_end

    @property
    def days(self):
        """Gets the days of this Arc2Cache.

        Rainfall cache size in number of days  # noqa: E501

        :return: The days of this Arc2Cache.
        :rtype: float
        """
        return self._days

    @days.setter
    def days(self, days):
        """Sets the days of this Arc2Cache.

        Rainfall cache size in number of days  # noqa: E501

        :param days: The days of this Arc2Cache.
        :type days: float
        """

        self._days = days

    @property
    def cache(self):
        """Gets the cache of this Arc2Cache.

        Rainfall cache content  # noqa: E501

        :return: The cache of this Arc2Cache.
        :rtype: List[str]
        """
        return self._cache

    @cache.setter
    def cache(self, cache):
        """Sets the cache of this Arc2Cache.

        Rainfall cache content  # noqa: E501

        :param cache: The cache of this Arc2Cache.
        :type cache: List[str]
        """

        self._cache = cache
