# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class BadRequestResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, object_type=None):  # noqa: E501
        """BadRequestResponse - a model defined in OpenAPI

        :param message: The message of this BadRequestResponse.  # noqa: E501
        :type message: str
        :param object_type: The object_type of this BadRequestResponse.  # noqa: E501
        :type object_type: str
        """
        self.openapi_types = {
            'message': str,
            'object_type': str
        }

        self.attribute_map = {
            'message': 'message',
            'object_type': 'object_type'
        }

        self._message = message
        self._object_type = object_type

    @classmethod
    def from_dict(cls, dikt) -> 'BadRequestResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BadRequestResponse of this BadRequestResponse.  # noqa: E501
        :rtype: BadRequestResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self):
        """Gets the message of this BadRequestResponse.

        Human readable error message  # noqa: E501

        :return: The message of this BadRequestResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this BadRequestResponse.

        Human readable error message  # noqa: E501

        :param message: The message of this BadRequestResponse.
        :type message: str
        """

        self._message = message

    @property
    def object_type(self):
        """Gets the object_type of this BadRequestResponse.

        Object type for this operation  # noqa: E501

        :return: The object_type of this BadRequestResponse.
        :rtype: str
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type):
        """Sets the object_type of this BadRequestResponse.

        Object type for this operation  # noqa: E501

        :param object_type: The object_type of this BadRequestResponse.
        :type object_type: str
        """

        self._object_type = object_type
