# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util

import re  # noqa: E501

class DataSet(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, season_id=None, folder_name=None, site_table_file=None):  # noqa: E501
        """DataSet - a model defined in OpenAPI

        :param id: The id of this DataSet.  # noqa: E501
        :type id: str
        :param season_id: The season_id of this DataSet.  # noqa: E501
        :type season_id: str
        :param folder_name: The folder_name of this DataSet.  # noqa: E501
        :type folder_name: str
        :param site_table_file: The site_table_file of this DataSet.  # noqa: E501
        :type site_table_file: str
        """
        self.openapi_types = {
            'id': str,
            'season_id': str,
            'folder_name': str,
            'site_table_file': str
        }

        self.attribute_map = {
            'id': 'id',
            'season_id': 'season_id',
            'folder_name': 'folder_name',
            'site_table_file': 'site_table_file'
        }

        self._id = id
        self._season_id = season_id
        self._folder_name = folder_name
        self._site_table_file = site_table_file

    @classmethod
    def from_dict(cls, dikt) -> 'DataSet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataSet of this DataSet.  # noqa: E501
        :rtype: DataSet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this DataSet.


        :return: The id of this DataSet.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DataSet.


        :param id: The id of this DataSet.
        :type id: str
        """
        if id is not None and len(id) > 64:
            raise ValueError("Invalid value for `id`, length must be less than or equal to `64`")  # noqa: E501
        if id is not None and len(id) < 1:
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `1`")  # noqa: E501

        self._id = id

    @property
    def season_id(self):
        """Gets the season_id of this DataSet.


        :return: The season_id of this DataSet.
        :rtype: str
        """
        return self._season_id

    @season_id.setter
    def season_id(self, season_id):
        """Sets the season_id of this DataSet.


        :param season_id: The season_id of this DataSet.
        :type season_id: str
        """
        if season_id is not None and not re.search(r'^[LS]R20[0-9]{2}$', season_id):  # noqa: E501
            raise ValueError("Invalid value for `season_id`, must be a follow pattern or equal to `/^[LS]R20[0-9]{2}$/`")  # noqa: E501

        self._season_id = season_id

    @property
    def folder_name(self):
        """Gets the folder_name of this DataSet.


        :return: The folder_name of this DataSet.
        :rtype: str
        """
        return self._folder_name

    @folder_name.setter
    def folder_name(self, folder_name):
        """Sets the folder_name of this DataSet.


        :param folder_name: The folder_name of this DataSet.
        :type folder_name: str
        """
        if folder_name is not None and len(folder_name) > 64:
            raise ValueError("Invalid value for `folder_name`, length must be less than or equal to `64`")  # noqa: E501
        if folder_name is not None and len(folder_name) < 1:
            raise ValueError("Invalid value for `folder_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._folder_name = folder_name

    @property
    def site_table_file(self):
        """Gets the site_table_file of this DataSet.


        :return: The site_table_file of this DataSet.
        :rtype: str
        """
        return self._site_table_file

    @site_table_file.setter
    def site_table_file(self, site_table_file):
        """Sets the site_table_file of this DataSet.


        :param site_table_file: The site_table_file of this DataSet.
        :type site_table_file: str
        """
        if site_table_file is not None and len(site_table_file) > 64:
            raise ValueError("Invalid value for `site_table_file`, length must be less than or equal to `64`")  # noqa: E501
        if site_table_file is not None and len(site_table_file) < 5:
            raise ValueError("Invalid value for `site_table_file`, length must be greater than or equal to `5`")  # noqa: E501

        self._site_table_file = site_table_file
