# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util

import re  # noqa: E501

class PolicyInfoAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, crop=None, location=None, sum_insured=None, begin_date=None, end_date=None):  # noqa: E501
        """PolicyInfoAllOf - a model defined in OpenAPI

        :param crop: The crop of this PolicyInfoAllOf.  # noqa: E501
        :type crop: str
        :param location: The location of this PolicyInfoAllOf.  # noqa: E501
        :type location: str
        :param sum_insured: The sum_insured of this PolicyInfoAllOf.  # noqa: E501
        :type sum_insured: float
        :param begin_date: The begin_date of this PolicyInfoAllOf.  # noqa: E501
        :type begin_date: str
        :param end_date: The end_date of this PolicyInfoAllOf.  # noqa: E501
        :type end_date: str
        """
        self.openapi_types = {
            'crop': str,
            'location': str,
            'sum_insured': float,
            'begin_date': str,
            'end_date': str
        }

        self.attribute_map = {
            'crop': 'crop',
            'location': 'location',
            'sum_insured': 'sum_insured',
            'begin_date': 'begin_date',
            'end_date': 'end_date'
        }

        self._crop = crop
        self._location = location
        self._sum_insured = sum_insured
        self._begin_date = begin_date
        self._end_date = end_date

    @classmethod
    def from_dict(cls, dikt) -> 'PolicyInfoAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PolicyInfo_allOf of this PolicyInfoAllOf.  # noqa: E501
        :rtype: PolicyInfoAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def crop(self):
        """Gets the crop of this PolicyInfoAllOf.

        Crop (also called value chain)  # noqa: E501

        :return: The crop of this PolicyInfoAllOf.
        :rtype: str
        """
        return self._crop

    @crop.setter
    def crop(self, crop):
        """Sets the crop of this PolicyInfoAllOf.

        Crop (also called value chain)  # noqa: E501

        :param crop: The crop of this PolicyInfoAllOf.
        :type crop: str
        """
        allowed_values = ["Maize", "Sorghum", "Greengrams", "Potato", "SoyBeans", "Wheat"]  # noqa: E501
        if crop not in allowed_values:
            raise ValueError(
                "Invalid value for `crop` ({0}), must be one of {1}"
                .format(crop, allowed_values)
            )

        self._crop = crop

    @property
    def location(self):
        """Gets the location of this PolicyInfoAllOf.

        Policy location  # noqa: E501

        :return: The location of this PolicyInfoAllOf.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this PolicyInfoAllOf.

        Policy location  # noqa: E501

        :param location: The location of this PolicyInfoAllOf.
        :type location: str
        """
        if location is not None and not re.search(r'^Pixel[0-9]{6}$', location):  # noqa: E501
            raise ValueError("Invalid value for `location`, must be a follow pattern or equal to `/^Pixel[0-9]{6}$/`")  # noqa: E501

        self._location = location

    @property
    def sum_insured(self):
        """Gets the sum_insured of this PolicyInfoAllOf.

        The sum insured for this policy  # noqa: E501

        :return: The sum_insured of this PolicyInfoAllOf.
        :rtype: float
        """
        return self._sum_insured

    @sum_insured.setter
    def sum_insured(self, sum_insured):
        """Sets the sum_insured of this PolicyInfoAllOf.

        The sum insured for this policy  # noqa: E501

        :param sum_insured: The sum_insured of this PolicyInfoAllOf.
        :type sum_insured: float
        """
        if sum_insured is not None and sum_insured > 1000000.0:  # noqa: E501
            raise ValueError("Invalid value for `sum_insured`, must be a value less than or equal to `1000000.0`")  # noqa: E501
        if sum_insured is not None and sum_insured < 0.0:  # noqa: E501
            raise ValueError("Invalid value for `sum_insured`, must be a value greater than or equal to `0.0`")  # noqa: E501

        self._sum_insured = sum_insured

    @property
    def begin_date(self):
        """Gets the begin_date of this PolicyInfoAllOf.

        The insurance coverage start date for this policy  # noqa: E501

        :return: The begin_date of this PolicyInfoAllOf.
        :rtype: str
        """
        return self._begin_date

    @begin_date.setter
    def begin_date(self, begin_date):
        """Sets the begin_date of this PolicyInfoAllOf.

        The insurance coverage start date for this policy  # noqa: E501

        :param begin_date: The begin_date of this PolicyInfoAllOf.
        :type begin_date: str
        """
        if begin_date is not None and not re.search(r'^20[0-9]{6}$', begin_date):  # noqa: E501
            raise ValueError("Invalid value for `begin_date`, must be a follow pattern or equal to `/^20[0-9]{6}$/`")  # noqa: E501

        self._begin_date = begin_date

    @property
    def end_date(self):
        """Gets the end_date of this PolicyInfoAllOf.

        The insurance coverage end date for this policy  # noqa: E501

        :return: The end_date of this PolicyInfoAllOf.
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this PolicyInfoAllOf.

        The insurance coverage end date for this policy  # noqa: E501

        :param end_date: The end_date of this PolicyInfoAllOf.
        :type end_date: str
        """
        if end_date is not None and not re.search(r'^20[0-9]{6}$', end_date):  # noqa: E501
            raise ValueError("Invalid value for `end_date`, must be a follow pattern or equal to `/^20[0-9]{6}$/`")  # noqa: E501

        self._end_date = end_date
